name: core
description: Shared core utilities, widgets, and services for the super app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation:
  freezed:
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  dartz: ^0.10.1
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  lokalise_flutter_sdk: ^2.0.0
  go_router: ^16.0.0
  envied: ^1.2.0
  file_picker: ^10.2.1
  image_picker: ^1.2.0
  skeletonizer: ^2.1.0+1
  webview_flutter: ^4.13.0
  geolocator: ^11.0.0
  geocoding: ^2.0.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  device_info_plus: ^12.2.0
  lottie: ^3.3.1
#  share_plus: ^8.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  retrofit_generator: ^9.2.0
  riverpod_generator: ^2.5.0
  flutter_gen_runner: ^5.10.0
  envied_generator: ^1.1.1
  json_serializable: ^6.9.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/loader/

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Light.ttf
          weight: 300
        - asset: assets/fonts/Onest-Regular.ttf
          weight: 400
        - asset: assets/fonts/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700
        - asset: assets/fonts/Onest-ExtraBold.ttf
          weight: 800


flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    lottie: true
  # Assets configuration
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true

  # Fonts configuration
  fonts:
    enabled: true
    outputs:
      package_parameter_enabled: true
